baseURL = "https://greggawatt.github.io"
languageCode = "en-us"
title = "Gregg(awatt)"
theme = "m10c"

[params]
    description = "Hi I'm Gregg Horton, I'm a security engineer, experimental artist, amateur radio operator (K6XSS), gardener and bicyclist. This is where I put my notes. "
    avatar = "https://pbs.twimg.com/profile_images/1335826029223428097/noa4zd2a_400x400.jpg"
    [[menu.main]]
        identifier = "talks"
        name = "Talks & Workshops"
        url = "/talks/"
    
    [[params.social]]
        name = "github"
        url = "https://github.com/greggawatt"
    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/greggawatt"
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/greggawatt/"